# <BC카드 Data 전처리>

In [112]:
import pandas as pd
import numpy as np

### 1. 데이터 불러오기

In [113]:
# 1.데이터 불러오기 
df_BC=pd.read_csv('C:\study\jeju_4.csv', encoding='cp949')
df_BC

,기준년월,관광객 유형,제주 대분류,제주 중분류,업종명,성별,연령대별,카드이용금액,카드이용건수,건당이용금액,데이터기준일자
0,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,여,50대,14434000,67,215433,2017-02-16
1,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,남,50대,15119000,72,209986,2017-02-16
2,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,여,40대,7609500,41,185598,2017-02-16
3,2014-09,내국인 관광객,서귀포시,남원읍,농축수산품,남,50대,7092500,40,177313,2017-02-16
4,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,남,40대,9098500,59,154212,2017-02-16
...,...,...,...,...,...,...,...,...,...,...,...
13141,2016-08,내국인 관광객,서귀포시,남원읍,약국,남,30대,252900,43,5881,2017-02-16
13142,2016-08,내국인 관광객,서귀포시,대륜동,약국,남,20대,276100,49,5635,2017-02-16
13143,2016-08,내국인 관광객,서귀포시,대륜동,기타음료식품,남,30대,610850,118,5177,2017-02-16
13144,2016-08,내국인 관광객,서귀포시,대륜동,기타음료식품,여,20대,416900,85,4905,2017-02-16
13145,2016-08,내국인 관광객,서귀포시,대륜동,기타음료식품,여,50대,56200,12,4683,2017-02-16

### 2. 변수 정보 확인

In [114]:
df_BC.shape

(13146, 11)

In [115]:
df_BC.info()    # Dtype확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13146 entries, 0 to 13145
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   기준년월      13146 non-null  object
 1   관광객 유형    13146 non-null  object
 2   제주 대분류    13146 non-null  object
 3   제주 중분류    13146 non-null  object
 4   업종명       13146 non-null  object
 5   성별        13146 non-null  object
 6   연령대별      13146 non-null  object
 7    카드이용금액   13146 non-null  int64
 8    카드이용건수   13146 non-null  int64
 9   건당이용금액    13146 non-null  int64
 10  데이터기준일자   13146 non-null  object
dtypes: int64(3), object(8)
memory usage: 1.1+ MB

In [116]:
df_BC.columns

Index(['기준년월', '관광객 유형', '제주 대분류', '제주 중분류', '업종명', '성별', '연령대별', ' 카드이용금액 ',
       ' 카드이용건수 ', '건당이용금액', '데이터기준일자'],
      dtype='object')

### 3. 결측치 확인

In [117]:
df_BC.isnull().sum()       # 결측치 없음 확인

기준년월        0
관광객 유형      0
제주 대분류      0
제주 중분류      0
업종명         0
성별          0
연령대별        0
 카드이용금액     0
 카드이용건수     0
건당이용금액      0
데이터기준일자     0
dtype: int64

### 4. 컬럼 정리

#### 기준년월 연도,월 분리

In [118]:
# 연도, 월 쪼개기 
data=pd.to_datetime(df_BC['기준년월'])

In [119]:
df_BC['연도'] = pd.to_datetime(data).dt.year  #연도
df_BC['월'] = pd.to_datetime(data).dt.month   #월

In [120]:
df_BC

,기준년월,관광객 유형,제주 대분류,제주 중분류,업종명,성별,연령대별,카드이용금액,카드이용건수,건당이용금액,데이터기준일자,연도,월
0,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,여,50대,14434000,67,215433,2017-02-16,2014,9
1,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,남,50대,15119000,72,209986,2017-02-16,2014,9
2,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,여,40대,7609500,41,185598,2017-02-16,2014,9
3,2014-09,내국인 관광객,서귀포시,남원읍,농축수산품,남,50대,7092500,40,177313,2017-02-16,2014,9
4,2014-09,내국인 관광객,서귀포시,대륜동,농축수산품,남,40대,9098500,59,154212,2017-02-16,2014,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13141,2016-08,내국인 관광객,서귀포시,남원읍,약국,남,30대,252900,43,5881,2017-02-16,2016,8
13142,2016-08,내국인 관광객,서귀포시,대륜동,약국,남,20대,276100,49,5635,2017-02-16,2016,8
13143,2016-08,내국인 관광객,서귀포시,대륜동,기타음료식품,남,30대,610850,118,5177,2017-02-16,2016,8
13144,2016-08,내국인 관광객,서귀포시,대륜동,기타음료식품,여,20대,416900,85,4905,2017-02-16,2016,8
13145,2016-08,내국인 관광객,서귀포시,대륜동,기타음료식품,여,50대,56200,12,4683,2017-02-16,2016,8

In [121]:
df_BC2=df_BC.drop(['기준년월'],axis=1)   # 기준년월 칼럼 삭제
df_BC2

,관광객 유형,제주 대분류,제주 중분류,업종명,성별,연령대별,카드이용금액,카드이용건수,건당이용금액,데이터기준일자,연도,월
0,내국인 관광객,서귀포시,대륜동,농축수산품,여,50대,14434000,67,215433,2017-02-16,2014,9
1,내국인 관광객,서귀포시,대륜동,농축수산품,남,50대,15119000,72,209986,2017-02-16,2014,9
2,내국인 관광객,서귀포시,대륜동,농축수산품,여,40대,7609500,41,185598,2017-02-16,2014,9
3,내국인 관광객,서귀포시,남원읍,농축수산품,남,50대,7092500,40,177313,2017-02-16,2014,9
4,내국인 관광객,서귀포시,대륜동,농축수산품,남,40대,9098500,59,154212,2017-02-16,2014,9
...,...,...,...,...,...,...,...,...,...,...,...,...
13141,내국인 관광객,서귀포시,남원읍,약국,남,30대,252900,43,5881,2017-02-16,2016,8
13142,내국인 관광객,서귀포시,대륜동,약국,남,20대,276100,49,5635,2017-02-16,2016,8
13143,내국인 관광객,서귀포시,대륜동,기타음료식품,남,30대,610850,118,5177,2017-02-16,2016,8
13144,내국인 관광객,서귀포시,대륜동,기타음료식품,여,20대,416900,85,4905,2017-02-16,2016,8
13145,내국인 관광객,서귀포시,대륜동,기타음료식품,여,50대,56200,12,4683,2017-02-16,2016,8

#### 분기 column 추가

In [122]:
# 분기 column 추가
df_BC2['분기'] = pd.to_datetime(data).dt.quarter   #분기

In [123]:
df_BC2

,관광객 유형,제주 대분류,제주 중분류,업종명,성별,연령대별,카드이용금액,카드이용건수,건당이용금액,데이터기준일자,연도,월,분기
0,내국인 관광객,서귀포시,대륜동,농축수산품,여,50대,14434000,67,215433,2017-02-16,2014,9,3
1,내국인 관광객,서귀포시,대륜동,농축수산품,남,50대,15119000,72,209986,2017-02-16,2014,9,3
2,내국인 관광객,서귀포시,대륜동,농축수산품,여,40대,7609500,41,185598,2017-02-16,2014,9,3
3,내국인 관광객,서귀포시,남원읍,농축수산품,남,50대,7092500,40,177313,2017-02-16,2014,9,3
4,내국인 관광객,서귀포시,대륜동,농축수산품,남,40대,9098500,59,154212,2017-02-16,2014,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13141,내국인 관광객,서귀포시,남원읍,약국,남,30대,252900,43,5881,2017-02-16,2016,8,3
13142,내국인 관광객,서귀포시,대륜동,약국,남,20대,276100,49,5635,2017-02-16,2016,8,3
13143,내국인 관광객,서귀포시,대륜동,기타음료식품,남,30대,610850,118,5177,2017-02-16,2016,8,3
13144,내국인 관광객,서귀포시,대륜동,기타음료식품,여,20대,416900,85,4905,2017-02-16,2016,8,3
13145,내국인 관광객,서귀포시,대륜동,기타음료식품,여,50대,56200,12,4683,2017-02-16,2016,8,3

#### 칼럼 순서 변경

In [124]:
columns=['연도','월','분기','제주 대분류','제주 중분류','업종명','성별','연령대별',' 카드이용금액 ',' 카드이용건수 ',
        '건당이용금액','관광객 유형']
df_BC3=df_BC2[columns]
df_BC3

,연도,월,분기,제주 대분류,제주 중분류,업종명,성별,연령대별,카드이용금액,카드이용건수,건당이용금액,관광객 유형
0,2014,9,3,서귀포시,대륜동,농축수산품,여,50대,14434000,67,215433,내국인 관광객
1,2014,9,3,서귀포시,대륜동,농축수산품,남,50대,15119000,72,209986,내국인 관광객
2,2014,9,3,서귀포시,대륜동,농축수산품,여,40대,7609500,41,185598,내국인 관광객
3,2014,9,3,서귀포시,남원읍,농축수산품,남,50대,7092500,40,177313,내국인 관광객
4,2014,9,3,서귀포시,대륜동,농축수산품,남,40대,9098500,59,154212,내국인 관광객
...,...,...,...,...,...,...,...,...,...,...,...,...
13141,2016,8,3,서귀포시,남원읍,약국,남,30대,252900,43,5881,내국인 관광객
13142,2016,8,3,서귀포시,대륜동,약국,남,20대,276100,49,5635,내국인 관광객
13143,2016,8,3,서귀포시,대륜동,기타음료식품,남,30대,610850,118,5177,내국인 관광객
13144,2016,8,3,서귀포시,대륜동,기타음료식품,여,20대,416900,85,4905,내국인 관광객
13145,2016,8,3,서귀포시,대륜동,기타음료식품,여,50대,56200,12,4683,내국인 관광객

### 5. 값 정리

#### value 확인

In [125]:
set(df_BC2['관광객 유형'])   # 관광객 유형 컬럼 value 확인

{'내국인 관광객'}

In [126]:
set(df_BC2['제주 대분류'] )    # 제주 대분류 컬럼 value 확인

{'서귀포시', '제주시'}

In [127]:
set(df_BC2['제주 중분류'] )    # 제주 중분류 컬럼 value 확인

{'남원읍', '노형동', '대륜동', '삼도2동', '성산읍', '애월읍', '연동', '예래동', '용담2동', '이도2동'}

In [128]:
set(df_BC2['업종명'] )    # 업종명 컬럼 value 확인

{'골프 용품',
 '귀 금 속',
 '기념품 점',
 '기타음료식품',
 '농축수산품',
 '슈퍼 마켓',
 '스넥',
 '스포츠레져용품',
 '신   발',
 '악세 사리',
 '안경',
 '약국',
 '의원',
 '정장(여성)'}

In [129]:
set(df_BC2['연령대별'] )    # 연령대별 컬럼 value 확인

{'20대', '30대', '40대', '50대'}

#### 업종명 값 공백 제거

In [130]:
value_shop=(df_BC3['업종명'])
value_shop

0         농축수산품
1         농축수산품
2         농축수산품
3         농축수산품
4         농축수산품
          ...
13141        약국
13142        약국
13143    기타음료식품
13144    기타음료식품
13145    기타음료식품
Name: 업종명, Length: 13146, dtype: object

In [131]:
value_shop.replace({'골프 용품':'골프용품',
 '귀 금 속':'귀금속',
 '기념품 점':'기념품점',
 '기타음료식품':'기타음료식품',
 '농축수산품':'농축수산품',
 '슈퍼 마켓':'슈퍼마켓',
 '스넥':'스낵',
 '스포츠레져용품':'스포츠레저용품',
 '신   발':'신발',
 '악세 사리':'악세서리',
 '안경':'안경',
 '약국':'약국',
 '의원':'의원',
 '정장(여성)':'여성정장'},inplace=True)

C:\Users\ajin1\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [132]:
set(value_shop)    # 값 공백 제거

{'골프용품',
 '귀금속',
 '기념품점',
 '기타음료식품',
 '농축수산품',
 '슈퍼마켓',
 '스낵',
 '스포츠레저용품',
 '신발',
 '악세서리',
 '안경',
 '약국',
 '여성정장',
 '의원'}

In [133]:
df_BC3

,연도,월,분기,제주 대분류,제주 중분류,업종명,성별,연령대별,카드이용금액,카드이용건수,건당이용금액,관광객 유형
0,2014,9,3,서귀포시,대륜동,농축수산품,여,50대,14434000,67,215433,내국인 관광객
1,2014,9,3,서귀포시,대륜동,농축수산품,남,50대,15119000,72,209986,내국인 관광객
2,2014,9,3,서귀포시,대륜동,농축수산품,여,40대,7609500,41,185598,내국인 관광객
3,2014,9,3,서귀포시,남원읍,농축수산품,남,50대,7092500,40,177313,내국인 관광객
4,2014,9,3,서귀포시,대륜동,농축수산품,남,40대,9098500,59,154212,내국인 관광객
...,...,...,...,...,...,...,...,...,...,...,...,...
13141,2016,8,3,서귀포시,남원읍,약국,남,30대,252900,43,5881,내국인 관광객
13142,2016,8,3,서귀포시,대륜동,약국,남,20대,276100,49,5635,내국인 관광객
13143,2016,8,3,서귀포시,대륜동,기타음료식품,남,30대,610850,118,5177,내국인 관광객
13144,2016,8,3,서귀포시,대륜동,기타음료식품,여,20대,416900,85,4905,내국인 관광객
13145,2016,8,3,서귀포시,대륜동,기타음료식품,여,50대,56200,12,4683,내국인 관광객

#### 칼럼명 변경

In [134]:
df_BC4=df_BC3.rename(columns={'연도':'연도','월':'월','제주 대분류':'시도명','제주 중분류':'읍면동명','업종명':'업종명',
                       '성별':'성별','연령대별':'연령대',' 카드이용금액 ':'카드이용금액',' 카드이용건수 ':'카드이용건수',
                       '건당이용금액':'건당이용금액','관광객 유형':'관광객'})
df_BC4

,연도,월,분기,시도명,읍면동명,업종명,성별,연령대,카드이용금액,카드이용건수,건당이용금액,관광객
0,2014,9,3,서귀포시,대륜동,농축수산품,여,50대,14434000,67,215433,내국인 관광객
1,2014,9,3,서귀포시,대륜동,농축수산품,남,50대,15119000,72,209986,내국인 관광객
2,2014,9,3,서귀포시,대륜동,농축수산품,여,40대,7609500,41,185598,내국인 관광객
3,2014,9,3,서귀포시,남원읍,농축수산품,남,50대,7092500,40,177313,내국인 관광객
4,2014,9,3,서귀포시,대륜동,농축수산품,남,40대,9098500,59,154212,내국인 관광객
...,...,...,...,...,...,...,...,...,...,...,...,...
13141,2016,8,3,서귀포시,남원읍,약국,남,30대,252900,43,5881,내국인 관광객
13142,2016,8,3,서귀포시,대륜동,약국,남,20대,276100,49,5635,내국인 관광객
13143,2016,8,3,서귀포시,대륜동,기타음료식품,남,30대,610850,118,5177,내국인 관광객
13144,2016,8,3,서귀포시,대륜동,기타음료식품,여,20대,416900,85,4905,내국인 관광객
13145,2016,8,3,서귀포시,대륜동,기타음료식품,여,50대,56200,12,4683,내국인 관광객

#### 불필요한 칼럼 삭제

In [135]:
set(df_BC4['관광객'])   # 내국인 관광객밖에 없음
df_BC5=df_BC4.drop(['관광객'],axis=1)   # 관광객 칼럼 삭제
df_BC5

         연도  월  분기   시도명 읍면동명     업종명 성별  연령대    카드이용금액  카드이용건수  건당이용금액
0      2014  9   3  서귀포시  대륜동   농축수산품  여  50대  14434000      67  215433
1      2014  9   3  서귀포시  대륜동   농축수산품  남  50대  15119000      72  209986
2      2014  9   3  서귀포시  대륜동   농축수산품  여  40대   7609500      41  185598
3      2014  9   3  서귀포시  남원읍   농축수산품  남  50대   7092500      40  177313
4      2014  9   3  서귀포시  대륜동   농축수산품  남  40대   9098500      59  154212
...     ... ..  ..   ...  ...     ... ..  ...       ...     ...     ...
13141  2016  8   3  서귀포시  남원읍      약국  남  30대    252900      43    5881
13142  2016  8   3  서귀포시  대륜동      약국  남  20대    276100      49    5635
13143  2016  8   3  서귀포시  대륜동  기타음료식품  남  30대    610850     118    5177
13144  2016  8   3  서귀포시  대륜동  기타음료식품  여  20대    416900      85    4905
13145  2016  8   3  서귀포시  대륜동  기타음료식품  여  50대     56200      12    4683

[13146 rows x 11 columns]

In [144]:
# df_BC5.to_csv('경로/파일명.csv')
df_BC5.to_csv('C:\study\제주_관광객_소비패턴_변화_분석_BC카드_빅데이터_내국인관광객.csv', index = False)

### 6. 최종 데이터셋

-------------------------

### 데이터 출처
* 공공데이터포털
: 제주특별자치도 개별관광(FIT) 증가에 따른 제주 관광객 소비패턴 변화 분석 BC카드 빅데이터 내국인관광객.csv

### 변수 설명

* 2014~2016년도 제주도 내 내국인 관광객의 업종, 성별, 연령대별 카드이용금액, 카드이용건수, 건당이용금액

|**변수명**|**값 설명**|
|:-----|:-----|
|**연도**|2014, 2015, 2016|
|**월**|1,2,3,4,5,6,7,8,9,10,11,12|
|**분기**|일 년을 4등분 한 3개월씩의 기간|
|**시도명**|서귀포시,제주시|
|**읍면동명**|남원읍,노형동,대륜동,삼도2동,성산읍,애월읍,연동,예래동,용담2동,이도2동|
|**업종명**|골프용품,귀금속,기념품점,기타음료식품,농축수산품,슈퍼마켓,스낵,스포츠레저용품,신발,악세서리,안경,약국,여성정장,의원|
|**성별**|남,여|
|**연령대**|20대,30대,40대,50대|
|**카드이용금액**|카드로 상품을 구매하거나 서비스를 이용한 금액|
|**카드이용건수**|카드로 상품을 구매하거나 서비스를 이용한 수|
|**건당이용금액**|카드이용금액/카드이용건수, 소수점 반올림|
|**관광객**|내국인|

In [136]:
df_BC5

         연도  월  분기   시도명 읍면동명     업종명 성별  연령대    카드이용금액  카드이용건수  건당이용금액
0      2014  9   3  서귀포시  대륜동   농축수산품  여  50대  14434000      67  215433
1      2014  9   3  서귀포시  대륜동   농축수산품  남  50대  15119000      72  209986
2      2014  9   3  서귀포시  대륜동   농축수산품  여  40대   7609500      41  185598
3      2014  9   3  서귀포시  남원읍   농축수산품  남  50대   7092500      40  177313
4      2014  9   3  서귀포시  대륜동   농축수산품  남  40대   9098500      59  154212
...     ... ..  ..   ...  ...     ... ..  ...       ...     ...     ...
13141  2016  8   3  서귀포시  남원읍      약국  남  30대    252900      43    5881
13142  2016  8   3  서귀포시  대륜동      약국  남  20대    276100      49    5635
13143  2016  8   3  서귀포시  대륜동  기타음료식품  남  30대    610850     118    5177
13144  2016  8   3  서귀포시  대륜동  기타음료식품  여  20대    416900      85    4905
13145  2016  8   3  서귀포시  대륜동  기타음료식품  여  50대     56200      12    4683

[13146 rows x 11 columns]

### 분석방향

- 카드이용금액 추이
- 카드이용건수 추이
- 건당이용금액 추이

연도별, 분기별, 월별, 성별, 연령대별




업종, 읍면동 데이터 부족

-------------------------------